spring.application.name=sigepaisa

# ---------- Base de datos ----------
spring.datasource.url=jdbc:postgresql://localhost:5432/sigepaisa
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------- JPA / Hibernate ----------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ---------- Thymeleaf ----------
spring.thymeleaf.cache=false

# ---------- Servidor ----------
server.port=8080
